image: ruby:latest

stages:
  - lint
  - test

variables:
  BUNDLE_PATH: vendor/bundle

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/bundle

before_script:
  - gem install bundler -v 2.4.10
  - bundle install --jobs $(nproc) --path $BUNDLE_PATH

# rubocop:
#   stage: lint
#   script:
#     - bundle exec rubocop

rspec:
  stage: test
  script:
    - bundle exec rspec
